# Generated by Django 5.2 on 2025-05-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_experience_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
