# Generated by Django 5.2 on 2025-05-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='image_path',
            field=models.CharField(max_length=250),
        ),
    ]
